spring:
  application:
    name: Kargo
  server:
    port: ${SERVER_PORT:8011}
  datasource:
    url: jdbc:postgresql://localhost:5432/ilerijava
    username: devuser
    password: devpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
